const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.solid,
		C3.Behaviors.Platform,
		C3.Behaviors.scrollto,
		C3.Behaviors.Flash,
		C3.Behaviors.jumpthru,
		C3.Behaviors.Sin,
		C3.Plugins.TiledBg,
		C3.Plugins.Text,
		C3.Behaviors.Anchor,
		C3.Plugins.Mouse,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Text.Acts.AddInstanceVar,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Sprite.Acts.AddInstanceVar,
		C3.Plugins.TiledBg.Acts.SetWidth,
		C3.Plugins.TiledBg.Exps.Width,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Behaviors.Flash.Cnds.IsFlashing,
		C3.Behaviors.Flash.Acts.Flash,
		C3.Plugins.TiledBg.Cnds.CompareWidth,
		C3.Plugins.Sprite.Acts.SetCollisions,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.Sprite.Exps.X,
		C3.Behaviors.Platform.Acts.SimulateControl,
		C3.Behaviors.scrollto.Acts.Shake,
		C3.Behaviors.solid.Acts.SetEnabled,
		C3.Behaviors.Platform.Acts.SetEnabled,
		C3.Plugins.Sprite.Acts.SetAnim
	];
};
self.C3_JsPropNameTable = [
	{Solid: 0},
	{orig: 0},
	{top: 0},
	{lives: 0},
	{Platform: 0},
	{ScrollTo: 0},
	{Flash: 0},
	{Player: 0},
	{Sprite: 0},
	{coin: 0},
	{Sprite2: 0},
	{Sprite3: 0},
	{Jumpthru: 0},
	{Sine: 0},
	{Sprite5: 0},
	{Sprite6: 0},
	{TiledBackground: 0},
	{Sprite4: 0},
	{Sprite7: 0},
	{Score: 0},
	{Anchor: 0},
	{score: 0},
	{Sprite8: 0},
	{TiledBackground2: 0},
	{Text2: 0},
	{play: 0},
	{quit: 0},
	{Mouse: 0},
	{TiledBackground3: 0},
	{coin_PNG3: 0},
	{Text: 0},
	{heart: 0},
	{TiledBackground4: 0},
	{TiledBackground5: 0},
	{move: 0},
	{patrol: 0},
	{marker: 0},
	{movefollow: 0},
	{follow: 0},
	{web: 0},
	{fire: 0}
];

self.InstanceType = {
	orig: class extends self.ISpriteInstance {},
	top: class extends self.ISpriteInstance {},
	Player: class extends self.ISpriteInstance {},
	Sprite: class extends self.ISpriteInstance {},
	coin: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	Sprite6: class extends self.ISpriteInstance {},
	TiledBackground: class extends self.ITiledBackgroundInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	Sprite7: class extends self.ISpriteInstance {},
	score: class extends self.ITextInstance {},
	Sprite8: class extends self.ISpriteInstance {},
	TiledBackground2: class extends self.ITiledBackgroundInstance {},
	Text2: class extends self.ITextInstance {},
	play: class extends self.ISpriteInstance {},
	quit: class extends self.ISpriteInstance {},
	Mouse: class extends self.IInstance {},
	TiledBackground3: class extends self.ITiledBackgroundInstance {},
	coin_PNG3: class extends self.ISpriteInstance {},
	Text: class extends self.ITextInstance {},
	lives: class extends self.ITiledBackgroundInstance {},
	heart: class extends self.ISpriteInstance {},
	TiledBackground4: class extends self.ITiledBackgroundInstance {},
	TiledBackground5: class extends self.ITiledBackgroundInstance {},
	patrol: class extends self.ISpriteInstance {},
	marker: class extends self.ISpriteInstance {},
	follow: class extends self.ISpriteInstance {},
	web: class extends self.ISpriteInstance {},
	fire: class extends self.ISpriteInstance {}
}